### ISSUE TITLE
Ask a request/question a service

### ISSUE THREAD

**Issue by glp1002** [glp1002/GESPRO_pr-cticas#36]

**Comment by gbd1004** [comment]
Hola buenos días, un problema ha hecho que esta tarea requiera más tiempo.

**Comment by gag1005** [comment]
Buenos dias, ¿Que problema tienes?

**Comment by gbd1004** [comment]
Problemas con el acceso al servidor.

**Comment by jzx1003** [comment]
Buenas, estamos trabajando en ello para intentar que afecte lo mínimo posible al resto de tareas.

**Comment by gbd1004** [comment]
Vale, muchas gracias.

**Comment by glp1002** [comment]
El problema ya está solucionado
Buenas tardes
